### ISSUE TITLE
Missing std/node module

### ISSUE THREAD

**Issue by ObserverOfTime** [xhayper/discord-rpc-deno#23]
**Describe the bug**

```
error: Module not found "https://deno.land/std@0.206.0/node/events.ts".
    at https://deno.land/x/discord_rpc_deno@v1.0.25/deps.ts:2:30
```

**To Reproduce**

Run `deno install https://deno.land/x/discord_rpc_deno@v1.0.25/mod.ts`

**Expected behavior**

The module is installed.

**Source code**

N/A

**(please complete the following information):**

- OS: Arch Linux
- OS Version: 6.5.8
- Discord Version: PTB 0.0.56

**Additional context**

v1.1.0 (which has not been published on deno.land) has the same issue.

**Comment by RuiNtD** [comment]
@xhayper The `std` package no longer includes the `node` compatibility modules. Those are now included in Deno itself using `node:events`

**Comment by xhayper** [comment]
Thank you for explanation @RuiNtD
